# Generated by Django 3.2 on 2021-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(default='', upload_to='product_logos', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
