# Generated by Django 3.0.13 on 2022-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220317_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(null=True, verbose_name='Price with sale'),
        ),
    ]
