# Generated by Django 3.0.13 on 2022-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price with sale'),
        ),
    ]
