# Generated by Django 3.0.13 on 2022-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220319_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='band_width',
            field=models.CharField(blank=True, max_length=255, verbose_name='Band Width:'),
        ),
        migrations.AddField(
            model_name='product',
            name='case_diameter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Case Diameter'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating',
            field=models.CharField(blank=True, max_length=255, verbose_name='Coating'),
        ),
        migrations.AddField(
            model_name='product',
            name='functions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Functions'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=255, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_clocks',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='water_resistance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Water resistance'),
        ),
    ]
