# Generated by Django 3.0.13 on 2021-12-08 19:57

import availability.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('products', '0006_auto_20210628_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=availability.models.AvailabilityField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='availability.Availability', verbose_name='Availability'),
        ),
    ]
