# Generated by Django 3.0.13 on 2022-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_logos', verbose_name='Logo'),
        ),
    ]
