# Generated by Django 3.0.13 on 2022-03-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220323_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='case_diameter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Case diameter'),
        ),
    ]
