# Generated by Django 3.0.13 on 2022-03-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220323_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=False, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='product_logos', verbose_name='Logo'),
        ),
    ]
