# Generated by Django 3.0.13 on 2022-01-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('mobile', models.CharField(max_length=255, verbose_name='Mobile number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('delivery_method', models.CharField(choices=[('NOVA-POSHTA', 'Nova-poshta'), ('UKR-POSHTA', 'Ukr-poshta'), ('Delivery-POSHTA', 'Delivery-poshta'), ('SELF-PICKUP', 'Self-pickup')], default='SELF-PICKUP', max_length=22)),
                ('delivery_district_address', models.CharField(blank=True, max_length=255, verbose_name='Delivery district address')),
                ('delivery_region_address', models.CharField(blank=True, max_length=255, verbose_name='Delivery district address')),
                ('post_office', models.CharField(blank=True, max_length=255, verbose_name='Post office')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
